### ISSUE TITLE
yootheme footer issue

### ISSUE THREAD

**Issue by SumCompanyInc** [conseilgouz/AutoReadMore-J4#10]
not sure you are able to troubleshoot with yootheme pro footer, but we have  found that your autoreadmore plugin causes an issue with the yootheme pro footer .. see yoututbe video : https://www.youtube.com/watch?v=c-8V3M9KUMg

**Comment by conseilgouz** [comment]
Hi,
Thank you for telling me about this issue.
I'm not a yootheme user.
Nevertheless, it may be possible to ignore footer position using autoreadmore parameters, specially "ignore context".
Did you try to set plugin's debug to Activate ? this should show you contexts called on your page.

**Comment by conseilgouz** [comment]
Hi again,
Try to add "text" in the exclude contexts list.
This should solve your issue.

**Comment by conseilgouz** [comment]
Let me know if AutoReadMore version 5.1.8 solves this issue.

**Comment by SumCompanyInc** [comment]
really amazing, @conseilgouz . i believe your update fixed the issue
