### ISSUE TITLE
Customizing behaviour ?

### ISSUE THREAD

**Issue by Chico0008** [conseilgouz/AutoReadMore-J4#16]
Hi
I'm trying this joomla plugin on our joomla 5 test site.

install is ok, but hwo can i customize behaviour, to set the auto read more button after x paragraph or images ?
or after a number en characters ?

**Comment by conseilgouz** [comment]
Hi,

There's a lack of documentation on this plugin and I'm working on it...

To customize the plugins behaviour, in your admin, click on Plugins button. 

You'll find the plugin by filtering plugins either by it title (depending on your language : readmore or lire) or by element (type readmore).

Pascal

**Comment by Chico0008** [comment]
Oh ok, thanks a lot, i was in system/plugin, but couldn't do anything more >_<

**Comment by conseilgouz** [comment]
Hi,

Just added a bit of documentation  [https://github.com/conseilgouz/AutoReadMore-J4/wiki](https://github.com/conseilgouz/AutoReadMore-J4/wiki)
