### ISSUE TITLE
Feature Request for Limiting "User Type Logged Only" to Specific Categories

### ISSUE THREAD

**Issue by PageRankKings** [conseilgouz/AutoReadMore-J4#19]
Firstly, I want to thank you for the AutoReadMore-J4 plugin. I absolutely love the "User Type Logged Only" setting, which helps me manage content visibility effectively. However, I would like to request an additional feature or tweak to the current functionality.

Currently, the "User Type Logged Only" setting applies globally, but I would love the ability to apply it selectively to specific categories. Ideally, I would like to use most of the plugin's features across all categories but restrict the "User Type Logged Only" functionality to certain categories. This would give more flexibility in managing different types of content for logged-in users and at the same time apply all the other setting across all categories.

Would it be possible to consider this feature for a future update? I'd really appreciate your thoughts on this.

Thank you for your work on this plugin, and I look forward to hearing from you!

Best regards,

**Comment by conseilgouz** [comment]
Thank you for this feature request.

[AutoReadmore Version 5.3.0](https://github.com/conseilgouz/AutoReadMore-J4/releases/download/5.3.0/AutoReadMore-J4-5.3.0.zip)  includes it.

Best regards,

Pascal
