### ISSUE TITLE
Read more button not multi language

### ISSUE THREAD

**Issue by johanpeters** [conseilgouz/AutoReadMore-J4#20]
Add a option for the custom read more button so it's support multi language.

**Comment by conseilgouz** [comment]
Nice one, I did not think about this.
Thank you for telling it me.
I'll check this as soon as possible and give you more info when I have an idea on how to implement that.
Pascal

**Comment by johanpeters** [comment]
Hello Pascal,
asuming that it uses the default readmore button value of the language
file.. so default it should be multilanguage.

only thing, when people would like to have a other value then the default
language value.
1. use language override (non plugin specific)
2. define value in the plugin.

perhaps a idea to add the cg_readmore to the language file of the plugin.
that way it can be multilanguage..
otherwise you should have multiple entries in the plugin, depending on the
amount of languages installed.. makes it complex.

or use a parameter for language and button text.
for example nl-NL, klik hier om verder te lezen..
                    en-EN, click here to read more..

etc.etc.

**Comment by conseilgouz** [comment]
Hi,
Version 5.3.2 handles multi-language readmore button text.
It detects whether your site in single or multi-languages mode.
In case of multi-languages site, you'll be able to enter text for every language.
So, in multi-languages site, ReadMore button text becomes : 
![readmore_multi](https://github.com/user-attachments/assets/3ac4e320-0f8d-4e0c-ac59-53d89d93e5ad)
Pascal
