### ISSUE TITLE
can't change settings: Joomla\CMS\Form\Form::validateField() rule `cgform` missing

### ISSUE THREAD

**Issue by catconner** [conseilgouz/AutoReadMore-J4#22]
Joomla version 3.10.12 (yes I know it needs upgrading, I'm currently doing so and I'm trying to replace the old version of AutoReadMore to make it compatible with the Joomla 4 upgrade)

Is this plugin still compatible with Joomla 3?

When I try to set and save the plugin settings, I get the error:

Joomla\CMS\Form\Form::validateField() rule `cgform` missing

It also seems the plugin isn't working even with the default settings.

**Comment by catconner** [comment]
Sorry, should have also included the call stack -- but it seems there is a validation rule being called that doesn't exist?

Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/Form/Form.php:2154
2 	Joomla\CMS\Form\Form->validateField() 	JROOT/libraries/src/Form/Form.php:1225
3 	Joomla\CMS\Form\Form->validate() 	JROOT/libraries/src/MVC/Model/FormModel.php:361
4 	Joomla\CMS\MVC\Model\FormModel->validate() 	JROOT/libraries/src/MVC/Controller/FormController.php:720
5 	Joomla\CMS\MVC\Controller\FormController->save() 	JROOT/libraries/src/MVC/Controller/BaseController.php:702
6 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/administrator/components/com_plugins/plugins.php:19
7 	require_once() 	JROOT/libraries/src/Component/ComponentHelper.php:402
8 	Joomla\CMS\Component\ComponentHelper::executeComponent() 	JROOT/libraries/src/Component/ComponentHelper.php:377
9 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:101
10 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:159
11 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:225
12 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/index.php:51

**Comment by catconner** [comment]
Ah in looking further, here on the Github page it says supports J4/J5 -- but the listing on the Joomla extensions site (https://extensions.joomla.org/extension/auto-read-more/) has a description that reads "Adds Readmore button automatically for Joomla 3.10/J4.x/J5.x articles". 

I guess this description is wrong?

**Comment by conseilgouz** [comment]
Hi,

Autoreadmore version 5.1.5 is supposed to be compatible with J3.10.

After upgrading to Joomla 4.x or 5.x, a J4.x/5.x compatible version of this plugin will be proposed : version 5.3.3.

I'm checking your issue and come back to you as soon as possible.

Pascal

**Comment by conseilgouz** [comment]
I just made some tries in a J3.10 website and I cannot reproduce your issue.
Which autoreadmore plugin version are you working with ?

**Comment by conseilgouz** [comment]
OK, I found it : it's possible to load latest version of the plugin in a Joomla 3.10 version when it should not.

I'm fixing it so that it loads the correct version when running J3.10. I'll let you know when it's available.

Kind regards,

Pascal

**Comment by catconner** [comment]
Thank you for the quick reply!  Just to confirm -- the version I downloaded and installed is indeed 5.3.3.  

I'm happy to install version 5.1.5 and then update it once I move to Joomla 4, but if you can correct the installer, that would be super.

**Comment by catconner** [comment]
I put in version 5.1.5 and it's working beautifully. Thank you again!

**Comment by conseilgouz** [comment]
Latest Version 5.3.4 blocks installation if Joomla 3.10 is detected; It then proposes a link to version 5.1.5.

Thank you telling me about this issue.

Kind regards,

Pascal
