### ISSUE TITLE
Exclude plugin from selected menu items

### ISSUE THREAD

**Issue by mariantanase** [conseilgouz/AutoReadMore-J4#3]
Hi,
I have a problem with the latest version of the plugin (v.3.0.8).
On a site where the plugin is activated, I have a menu item who points to a contact form (Convert Form component).
On this page, the plugin takes away my last buttons and trim the text.
Efectively hides the submit button from me.
How can I exclude the plugin from a menu item ?

**Comment by conseilgouz** [comment]
Hi,
Did you try to disable other contexts ?
Another way is to enable debug (first parameter of the plugin) and check which context is used when calling convert form. After a quick try, it seems to be mod_custom.content.
Then disable this specific context by adding it in the context list.

**Comment by mariantanase** [comment]
Ok, I enabled debugging and noticed that context "text" was the one who causing problems, and after added "text" in the context list field, everything is fixed.
Thanks
