### ISSUE TITLE
Non funziona

### ISSUE THREAD

**Issue by tecnico10** [conseilgouz/AutoReadMore-J4#4]
Inserendo il plugin seguente:
https://extensions.hepta.es/joomla-extensions/estimated-reading-time
nella pagina dell'elenco degli articoli di una categoria il calcolo è sempre di 1 minuto.

https://www.vincenzodigiacomo.it/appunti-di-scrittura

Saluti

**Comment by conseilgouz** [comment]
Hi,
I just downloaded estimated-reading-time plugin and was not able to reproduce your issue.

You may see this on my blog page  https://www.conseilgouz.com/espace-tests

I also tried with Cassiopeia template and did not notice any problem.

Could you send me a copy of AutoReadMore and Estimated reading Time plugins parameters ?

Pascal

**Comment by tecnico10** [comment]
![Immagine 2023-01-06 174159](https://user-images.githubusercontent.com/1893680/211057320-cf584bc2-fc66-433b-8890-a379cc3890cb.jpg)
![Immagine 2023-01-06 174121](https://user-images.githubusercontent.com/1893680/211057325-ca40e9cd-e906-44b3-b63c-dd07277105d1.jpg)
![Immagine 2023-01-06 174046](https://user-images.githubusercontent.com/1893680/211057326-1f408726-283d-43b8-89a6-e468d5ac8678.jpg)
![Immagine 2023-01-06 174028](https://user-images.githubusercontent.com/1893680/211057328-5c50c254-0a95-4412-9ad7-ec18458e5d10.jpg)
![Immagine 2023-01-06 173959](https://user-images.githubusercontent.com/1893680/211057330-ec32c774-c968-4bb3-aa96-174bdd9fd1bc.jpg)

Tempo di lettura

**Comment by tecnico10** [comment]
![Immagine 2023-01-06 175407](https://user-images.githubusercontent.com/1893680/211059527-627034a5-e44b-4e9b-8b8c-95260e96bd86.jpg)
![Immagine 2023-01-06 175344](https://user-images.githubusercontent.com/1893680/211059533-db57f405-199b-497d-ba8d-0b37a50206dd.jpg)
![Immagine 2023-01-06 175306](https://user-images.githubusercontent.com/1893680/211059535-73d7d294-e0be-4969-aa12-e5f734c529d8.jpg)
![Immagine 2023-01-06 175248](https://user-images.githubusercontent.com/1893680/211059539-740ef68e-ebe7-4f86-9cb6-c49b93ff90d6.jpg)
![Immagine 2023-01-06 175223](https://user-images.githubusercontent.com/1893680/211059540-79b2ac9e-eb81-44c0-8300-46b92521651b.jpg)
![Immagine 2023-01-06 175155](https://user-images.githubusercontent.com/1893680/211059543-c6eaf65c-4e51-4885-a198-df6f89b9dc4d.jpg)
![Immagine 2023-01-06 175004](https://user-images.githubusercontent.com/1893680/211059545-3f739484-e3b7-4999-8027-7d9dc74bdcec.jpg)


Autoreadmore

**Comment by tecnico10** [comment]
Grazie

**Comment by conseilgouz** [comment]
For the record : 

This issue is due to the fact that Reading Time plugin uses onContentBeforeDisplay instead of onContentPrepare function. This means that plugins ordering could not solve this issue.

If no "readmore' appears in an article, content introtext is ok, but fulltext is empty. AutoreadMore replaces the content of introtext by its trucated value and left fulltext empty.

With version 5.0.9, if fulltext is empty, it is filled up with introtext.

**Comment by tecnico10** [comment]
ok risolto, grazie.
