### ISSUE TITLE
Changes text styles and colors

### ISSUE THREAD

**Issue by trogladyte** [conseilgouz/AutoReadMore-J4#6]
First, thanks for continuing this plugin on and filling a huge hole in the Joomla core.

However.... I installed it on a site tonight, and it had unexpected consequences. I use JoomlaCK's PageBuilderCK to do my regular articles. The plugin inserted Read Mores as I set it up to do. But it made some small text (11px font size) display as regular body text (16px) and changed some link colors. 

Strange thing is it wasn't every article; just seemed to do it randomly. All articles were pretty much exactly the same layout, so the misbehaving ones weren't vastly different to the others that were OK.

**Comment by conseilgouz** [comment]
Thank you for your support.
AutoReadmore plugin just adds a readmore button. It does not update CSS.
Before adding the button, it closes opened tags like div, p, ul, ....
Your issue sounds like an unclosed tag, meaming an unexpected (unhandled) tag.
Please give a site url where I could check this.
Kind regards,
Pascal

**Comment by conseilgouz** [comment]
No answer, closing issue
