### ISSUE TITLE
Call to undefined method stdClass::get()

### ISSUE THREAD

**Issue by SumCompanyInc** [conseilgouz/AutoReadMore-J4#7]
amazing work - love the plugin, at least the concept.. it doesnt work on a site where we are using sp page builder. not sure if its that, or what. but  just thought i've throw this out here in case you wanted to know. i can add more details if you have any more questions. 

`<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(34, 38, 42); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If difficulties persist, please contact the website administrator and report the error below.</p><blockquote style="box-sizing: border-box; margin: 0px 0px 1rem; color: rgb(34, 38, 42); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; --bs-badge-padding-x: 0.65em; --bs-badge-padding-y: 0.35em; --bs-badge-font-size: 0.75em; --bs-badge-font-weight: 700; --bs-badge-color: #fff; --bs-badge-border-radius: var(--bs-border-radius); display: inline-block; padding: var(--badge-padding-y) var(--badge-padding-x); font-size: var(--badge-font-size); font-weight: var(--badge-font-weight); line-height: 1; color: var(--badge-color); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: var(--badge-border-radius); --bs-bg-opacity: 1; background-color: var(--secondary) !important; --badge-padding-x: .65em; --badge-padding-y: .35em; --badge-font-size: .75em; --badge-font-weight: 700; --badge-color: #fff; --badge-border-radius: var(--border-radius); --bg-opacity: 1;">0</span><span> </span>Call to undefined method stdClass::get()</blockquote><div style="box-sizing: border-box; color: rgb(34, 38, 42); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Call stack
--
# | Function | Location
1 | () | JROOT/plugins/content/autoreadmore/autoreadmore.php:91
2 | PlgContentAutoReadMore->onContentPrepare() | JROOT/libraries/src/Plugin/CMSPlugin.php:289
3 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() |  
4 | call_user_func() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/JoomlaShim.php:138
5 | Nextend\SmartSlider3\Platform\Joomla\JoomlaShim::triggerOnContentPrepare() | JROOT/libraries/smartslider3/src/SmartSlider3/Slider/Joomla/PlatformSlider.php:28
6 | Nextend\SmartSlider3\Slider\Joomla\PlatformSlider->addCMSFunctions() | JROOT/libraries/smartslider3/src/SmartSlider3/Slider/Base/PlatformSliderTrait.php:22
7 | Nextend\SmartSlider3\Slider\Slider->addCMSFunctions() | JROOT/libraries/smartslider3/src/SmartSlider3/SliderManager/SliderManager.php:109
8 | Nextend\SmartSlider3\SliderManager\SliderManager->render() | JROOT/libraries/smartslider3/src/SmartSlider3/Application/Frontend/Slider/ViewDisplay.php:28
9 | Nextend\SmartSlider3\Application\Frontend\Slider\ViewDisplay->display() | JROOT/libraries/smartslider3/src/SmartSlider3/Application/Frontend/Slider/ControllerSlider.php:18
10 | Nextend\SmartSlider3\Application\Frontend\Slider\ControllerSlider->actionDisplay() |  
11 | call_user_func_array() | JROOT/libraries/smartslider3/src/Framework/Controller/AbstractController.php:92
12 | Nextend\Framework\Controller\AbstractController->doAction() | JROOT/libraries/smartslider3/src/Framework/Application/AbstractApplicationType.php:88
13 | Nextend\Framework\Application\AbstractApplicationType->process() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/compat.php:10
14 | nextend_smartslider3() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/Plugin/PluginSmartSlider3.php:148
15 | Nextend\SmartSlider3\Platform\Joomla\Plugin\PluginSmartSlider3::prepare() |  
16 | preg_replace_callback() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/Plugin/PluginSmartSlider3.php:73
17 | Nextend\SmartSlider3\Platform\Joomla\Plugin\PluginSmartSlider3->displaySliders() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/Plugin/PluginSmartSlider3.php:102
18 | Nextend\SmartSlider3\Platform\Joomla\Plugin\PluginSmartSlider3->onNextendBeforeCompileHead() | JROOT/libraries/smartslider3/src/SmartSlider3/Platform/Joomla/Plugin/PluginSmartSlider3.php:119
19 | Nextend\SmartSlider3\Platform\Joomla\Plugin\PluginSmartSlider3->onAfterRender() | JROOT/libraries/src/Plugin/CMSPlugin.php:289
20 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
21 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
22 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/Application/CMSApplication.php:1031
23 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:724
24 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:298
25 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
26 | require_once() | JROOT/index.php:32

</div>`

**Comment by conseilgouz** [comment]
Hi,
Thank you for your support.
You issue seems to be related to SmartSlider 3.
I just download latest version (3.5.1.20) and I can't find the same lines as shown in your log. For example, libraries/smartslider3/src/SmartSlider3/Platform/Joomla/JoomlaShim.php:138 contains }
Did you try to update SmartSlider ?
Regards,
Pascal

**Comment by conseilgouz** [comment]
Hi again,

I just tried with version 3.5.1.20 and been able to reproduce your issue (with new lines but same modules).

I'll let you know as soon as I find something.

Pascal

**Comment by conseilgouz** [comment]
Instead of being a Registry class, $params is an empty object in SmartSlider 3 causing this issue.
AutoReadMore has been updated to handle this in version 5.1.3.

**Comment by SumCompanyInc** [comment]
wow! amazing! it works! thank you!
