### ISSUE TITLE
Feature article setting is ignored

### ISSUE THREAD

**Issue by johanpeters** [conseilgouz/AutoReadMore-J4#8]
on the plugin i have configured that it should not run on feature articles.
result i expact is that all other articles triggered by the plugin excluding the featured articles.

but the result is that also the articles that are flagged as Special are also triggered by the plugin.

**Comment by conseilgouz** [comment]
Feature articles parameter says : Enable for Featured Articles component (Front Page component)

It's not used to show/hide feature articles.

**Comment by johanpeters** [comment]
hello,
i know and understand.. what it should do if feature articles disabled it should not add autoreadmore to that article.
that way, feature / special articles are published completly and only non special articles are getting hit by this plugin.

but even when you disable feature plugin setting it still adds readmore to special articles..

**Comment by conseilgouz** [comment]
Hi,
Version 5.1.4 has a new parameter "Featured articles (Blog)" to allow/ignore autoreadmore for Featured Articles while displayed in Category Blog mode.
In the parameters, I made a difference betwwen Featured Items (Front Page) ans Featured Items (Blog).
Just hope this solves current issue.
Pascal
